"""Fix GoodsReceipt model relationships

Revision ID: 1ab97284dcc5
Revises: 50ef2dd4ea7a
Create Date: 2025-05-31 06:22:57.268199

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1ab97284dcc5"
down_revision = "50ef2dd4ea7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables exist before dropping them
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    # Drop the existing tables in the correct order only if they exist
    if "goods_receipt_item" in existing_tables:
        op.drop_table("goods_receipt_item")

    if "goods_receipt" in existing_tables:
        op.drop_table("goods_receipt")

    # Create goods_receipt table first
    op.create_table(
        "goods_receipt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("receipt_number", sa.String(length=50), nullable=True),
        sa.Column("receipt_date", sa.Date(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_goods_receipt_user_id"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create goods_receipt_item table with receipt_id column
    op.create_table(
        "goods_receipt_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("receipt_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity_received", sa.Integer(), nullable=False),
        sa.Column("quantity_remaining", sa.Integer(), nullable=False),
        sa.Column("cost_price_per_unit", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("receipt_date", sa.DateTime(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("batch_number", sa.String(length=50), nullable=True),
        sa.Column("supplier_info", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], name="fk_goods_receipt_item_product_id"),
        sa.ForeignKeyConstraint(["receipt_id"], ["goods_receipt.id"], name="fk_goods_receipt_item_receipt_id"),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables exist before dropping them
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    # Drop the tables in the correct order only if they exist
    if "goods_receipt_item" in existing_tables:
        op.drop_table("goods_receipt_item")

    if "goods_receipt" in existing_tables:
        op.drop_table("goods_receipt")

    # Recreate goods_receipt table without user_id foreign key
    op.create_table(
        "goods_receipt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("receipt_number", sa.String(length=50), nullable=True),
        sa.Column("receipt_date", sa.Date(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # Recreate goods_receipt_item table without receipt_id column
    op.create_table(
        "goods_receipt_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity_received", sa.Integer(), nullable=False),
        sa.Column("quantity_remaining", sa.Integer(), nullable=False),
        sa.Column("cost_price_per_unit", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("receipt_date", sa.DateTime(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("batch_number", sa.String(length=50), nullable=True),
        sa.Column("supplier_info", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], name="fk_goods_receipt_item_product_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
