"""Allow nullable min_stock_level in Product model

Revision ID: 2ea257154bf4
Revises: bd27a33f7c4f
Create Date: 2025-05-31 17:09:29.113108

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = "2ea257154bf4"
down_revision = "bd27a33f7c4f"
branch_labels = None
depends_on = None


def upgrade():
    # Disable foreign key constraints for SQLite
    bind = op.get_bind()
    if bind.engine.name == "sqlite":
        bind.execute(text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("appointment", schema=None) as batch_op:
        batch_op.alter_column(
            "payment_status",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=20),
            existing_nullable=False,
            existing_server_default=sa.text("'unpaid'"),
        )
        batch_op.drop_column("total_price")

    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.alter_column("min_stock_level", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.alter_column(
            "base_price",
            existing_type=sa.REAL(),
            type_=sa.Float(),
            existing_nullable=True,
            existing_server_default=sa.text("(0.0)"),
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active_master", existing_type=sa.BOOLEAN(), nullable=False, existing_server_default=sa.text("0")
        )

    # ### end Alembic commands ###


def downgrade():
    # Disable foreign key constraints for SQLite
    bind = op.get_bind()
    if bind.engine.name == "sqlite":
        bind.execute(text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active_master", existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text("0")
        )

    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.alter_column(
            "base_price",
            existing_type=sa.Float(),
            type_=sa.REAL(),
            existing_nullable=True,
            existing_server_default=sa.text("(0.0)"),
        )

    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.alter_column("min_stock_level", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("appointment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("total_price", sa.REAL(), nullable=True))
        batch_op.alter_column(
            "payment_status",
            existing_type=sa.String(length=20),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
            existing_server_default=sa.text("'unpaid'"),
        )

    # ### end Alembic commands ###
