"""Fix appointment payment method column

Revision ID: 50ef2dd4ea7a
Revises: ae70f24bc602
Create Date: 2025-05-30 16:38:09.827910

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = "50ef2dd4ea7a"
down_revision = "ae70f24bc602"
branch_labels = None
depends_on = None


def upgrade():
    # Тимчасово вимкнути перевірку зовнішніх ключів для SQLite
    bind = op.get_bind()
    if bind.engine.name == "sqlite":
        bind.execute(text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("appointment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payment_method_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_appointment_payment_method", "payment_method", ["payment_method_id"], ["id"])
        batch_op.drop_column("payment_method")

    # ### end Alembic commands ###


def downgrade():
    # Тимчасово вимкнути перевірку зовнішніх ключів для SQLite
    bind = op.get_bind()
    if bind.engine.name == "sqlite":
        bind.execute(text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("appointment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payment_method", sa.VARCHAR(length=6), nullable=True))
        batch_op.drop_constraint("fk_appointment_payment_method", type_="foreignkey")
        batch_op.drop_column("payment_method_id")

    # ### end Alembic commands ###
