"""Add sales models and FIFO logic

Revision ID: ae70f24bc602
Revises: eab9c913ba1e
Create Date: 2025-05-30 16:36:15.381233

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = "ae70f24bc602"
down_revision = "eab9c913ba1e"
branch_labels = None
depends_on = None


def upgrade():
    # Тимчасово вимкнути перевірку зовнішніх ключів для SQLite
    bind = op.get_bind()
    if bind.engine.name == "sqlite":
        bind.execute(text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_method",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "goods_receipt_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity_received", sa.Integer(), nullable=False),
        sa.Column("quantity_remaining", sa.Integer(), nullable=False),
        sa.Column("cost_price_per_unit", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("receipt_date", sa.DateTime(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("batch_number", sa.String(length=50), nullable=True),
        sa.Column("supplier_info", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sale",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sale_date", sa.DateTime(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("payment_method_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["payment_method.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sale_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sale_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price_per_unit", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cost_price_per_unit", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"],
            ["sale.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("appointment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payment_method_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_appointment_payment_method", "payment_method", ["payment_method_id"], ["id"])
        batch_op.drop_column("payment_method")

    # ### end Alembic commands ###


def downgrade():
    # Тимчасово вимкнути перевірку зовнішніх ключів для SQLite
    bind = op.get_bind()
    if bind.engine.name == "sqlite":
        bind.execute(text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("appointment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payment_method", sa.VARCHAR(length=6), nullable=True))
        batch_op.drop_constraint("fk_appointment_payment_method", type_="foreignkey")
        batch_op.drop_column("payment_method_id")

    op.drop_table("sale_item")
    op.drop_table("sale")
    op.drop_table("goods_receipt_item")
    op.drop_table("payment_method")
    # ### end Alembic commands ###
