"""Add sales to appointment relationship with back_populates

Revision ID: b96600abf85c
Revises: 1ab97284dcc5
Create Date: 2025-05-31 09:22:25.591793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96600abf85c'
down_revision = '1ab97284dcc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_goods_receipt_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_goods_receipt_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity_received', sa.INTEGER(), nullable=False),
    sa.Column('quantity_remaining', sa.INTEGER(), nullable=False),
    sa.Column('cost_price_per_unit', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('receipt_date', sa.DATETIME(), nullable=False),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('batch_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('supplier_info', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('receipt_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['goods_receipt.id'], name='fk_goods_receipt_item_receipt_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
