"""Add inventory acts functionality

Revision ID: bd27a33f7c4f
Revises: 39b23e8c642c
Create Date: 2025-05-31 13:05:44.251426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd27a33f7c4f'
down_revision = '39b23e8c642c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_act',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_act_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_act_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Integer(), nullable=True),
    sa.Column('discrepancy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_act_id'], ['inventory_act.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_act_item')
    op.drop_table('inventory_act')
    # ### end Alembic commands ###
