"""Add configurable_commission_rate to User model

Revision ID: eab9c913ba1e
Revises: 1d436bddff8f
Create Date: 2025-05-30 15:56:18.423996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab9c913ba1e'
down_revision = '1d436bddff8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('configurable_commission_rate', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('configurable_commission_rate')

    # ### end Alembic commands ###
